### ISSUE TITLE
Дизайн-мышление

### ISSUE THREAD

**Issue by Patr56** [anatse/estima#3]
Нужен макет интерфейса.
Список RESTов.
(Хороший инструмент для наброска https://balsamiq.com/products/mockups/)

**Comment by anatse** [comment]
Список реализованных, на текущий момент рестов, доступен с помощью реста localhost:9080/ri
Все сервисы в качестве ответа используют объект **ResponseObj**, который состоит из следующих полей

- success - флаг успешности операции
- error - сообщение об ошибке, если есть
- body - тело сообщения, заполняется в зависимости от того, что ожидается в ответ от сервиса, массив или объект

**Comment by anatse** [comment]
Создал проект https://estima.mybalsamiq.com/projects/estima/grid

**Comment by Patr56** [comment]
@anatse  нету доступа к макету. Скрины может приложешь к issues?

Пишет:
401: Not Authorized
We're Sorry
Somehow we've gotten to an address that we can't display.

It's probably our fault, but this sometimes happens if you're trying to access an address that you haven't been given permission to view. If you were looking for a specific page that you can't find, please trying contacting the site owner, or email Balsamiq Support for further assistance.

Пользователя надо добавить именно в проект https://estima.mybalsamiq.com/.

**Comment by anatse** [comment]
Давай добавлю тебя, почта нужна, в телеграм кинь свою

**Comment by Patr56** [comment]
Подобавлял макетов к таскам)
