### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by anatse** [anatse/estima#4]
Необходимо создать страницу для входа пользователя.
1. Страница должна использовать сервис аутентификации /login. Сервис вызывается методом  POST. В качестве тела используется значения следующего вида
`{
    "uname": "имя пользователя",
    "upass": "пароль"
}`
В качестве ответа используется, как и во всех других сервисах, объект ResponseObj
`{success: boolean, error: string, body: entity}`

Макет https://estima.mybalsamiq.com/projects/estima/Login

В случае удачного входа, должен осуществляться переход к странице проектов пользователя

**Comment by Patr56** [comment]
![2017-04-24_21-11-04](https://cloud.githubusercontent.com/assets/5564729/25351831/8d5655f0-2932-11e7-9a2b-0199084ba1ac.png)
