### ISSUE TITLE
Страница редактирования проекта

### ISSUE THREAD

**Issue by anatse** [anatse/estima#6]
Макет: https://estima.mybalsamiq.com/projects/estima/Project%20settings
Используемые сервисы
- Информация о конкретном проекте - /project/{id}, где id - номер проекта
- Сохранение проекта - /project/create, в теле запроса передается структура типа:
`
{
   "number": "xxx",
   "description": "xxx",
   "status": "xxx"
}
`
- Список пользователей в проекте (с ролями) - /project/{id}/user/list
- Изменение статуса проекта - /project/{id}/status
- Добавление пользователя - /project/{id}/user/add, тело `{"name": "username", "role":"role"}`
- Удаление пользователя -

**Comment by Patr56** [comment]
![2017-04-24_21-08-02](https://cloud.githubusercontent.com/assets/5564729/25351727/3fad509c-2932-11e7-93b4-48803f6dd225.png)
